apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8jji
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-8jji@sha256:b709046df5a81ade4697e4bd78b035da41a2be151b4526e7024667f5ee9d5287
        name: my-nodejs
        resources: {}
status: {}
